import { Transaction } from '../types';

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // ==================== AUGUST 2026 (Current Month) ====================
  // Today / Recent
  {
    id: 'tx-aug-01',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 20,
    date: '2026-08-25T17:45:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from 12 previous payments',
    status: 'completed',
    note: 'Evening tea & biscuits',
  },
  {
    id: 'tx-aug-02',
    recipient: 'Swiggy',
    upiId: 'swiggy@icici',
    amount: 250,
    date: '2026-08-25T13:30:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Swiggy (Food)',
    status: 'completed',
  },
  {
    id: 'tx-aug-03',
    recipient: 'Uber',
    upiId: 'uber.india@hdfcbank',
    amount: 320,
    date: '2026-08-25T09:15:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Uber (Transport)',
    status: 'completed',
  },
  {
    id: 'tx-aug-04',
    recipient: 'Myntra',
    upiId: 'myntrapay@icici',
    amount: 1500,
    date: '2026-08-24T20:10:00',
    category: 'Shopping',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Myntra (Shopping)',
    status: 'completed',
  },
  {
    id: 'tx-aug-05',
    recipient: 'Netflix',
    upiId: 'netflix.india@axisbank',
    amount: 199,
    date: '2026-08-24T10:00:00',
    category: 'Entertainment',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Netflix (Entertainment)',
    status: 'completed',
  },

  // Multi-purpose recipient transactions (Rohit Kumar)
  {
    id: 'tx-aug-06',
    recipient: 'Rohit Kumar',
    upiId: 'rohit.kumar99@paytm',
    amount: 300,
    date: '2026-08-23T19:30:00',
    category: 'Food',
    classificationType: 'multi_purpose_suggested',
    confidence: 0.75,
    classificationReason: 'Suggested Food (40% frequency for Rohit Kumar)',
    status: 'completed',
    note: 'Dinner split at hostel mess',
  },
  {
    id: 'tx-aug-07',
    recipient: 'Rohit Kumar',
    upiId: 'rohit.kumar99@paytm',
    amount: 500,
    date: '2026-08-18T14:15:00',
    category: 'Personal',
    classificationType: 'user_classified',
    confidence: 0.85,
    classificationReason: 'User classified as Personal transfer',
    status: 'completed',
    note: 'Room rent share advance',
  },
  {
    id: 'tx-aug-08',
    recipient: 'Rohit Kumar',
    upiId: 'rohit.kumar99@paytm',
    amount: 1000,
    date: '2026-08-10T11:00:00',
    category: 'Education',
    classificationType: 'user_classified',
    confidence: 0.9,
    classificationReason: 'User classified as Education (shared textbook cost)',
    status: 'completed',
    note: 'Engineering Mathematics book split',
  },
  {
    id: 'tx-aug-09',
    recipient: 'Rohit Kumar',
    upiId: 'rohit.kumar99@paytm',
    amount: 250,
    date: '2026-08-05T16:00:00',
    category: 'Food',
    classificationType: 'multi_purpose_suggested',
    confidence: 0.75,
    classificationReason: 'Suggested Food (40% frequency)',
    status: 'completed',
  },

  // Ramesh Kumar Chai / Snacks sequence (Learned Memory)
  {
    id: 'tx-aug-10',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 30,
    date: '2026-08-23T08:30:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-11',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 25,
    date: '2026-08-22T17:15:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-12',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 40,
    date: '2026-08-20T17:00:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-13',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 15,
    date: '2026-08-19T08:45:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-14',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 35,
    date: '2026-08-17T18:00:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-15',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 20,
    date: '2026-08-15T16:30:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-16',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 50,
    date: '2026-08-13T17:40:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-17',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 25,
    date: '2026-08-11T09:00:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-18',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 30,
    date: '2026-08-08T17:20:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-19',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 20,
    date: '2026-08-04T18:10:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-aug-20',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 30,
    date: '2026-08-01T08:50:00',
    category: 'Food',
    classificationType: 'user_classified',
    confidence: 0.95,
    classificationReason: 'User classified as Food on initial payment',
    status: 'completed',
  },

  // Major food expenses
  {
    id: 'tx-aug-21',
    recipient: 'Zomato',
    upiId: 'zomato@hdfcbank',
    amount: 480,
    date: '2026-08-22T21:00:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Zomato (Food)',
    status: 'completed',
  },
  {
    id: 'tx-aug-22',
    recipient: 'Zomato',
    upiId: 'zomato@hdfcbank',
    amount: 360,
    date: '2026-08-16T20:30:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Zomato (Food)',
    status: 'completed',
  },
  {
    id: 'tx-aug-23',
    recipient: 'Swiggy',
    upiId: 'swiggy@icici',
    amount: 420,
    date: '2026-08-12T13:40:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Swiggy (Food)',
    status: 'completed',
  },
  {
    id: 'tx-aug-24',
    recipient: 'Blinkit',
    upiId: 'blinkit@icici',
    amount: 650,
    date: '2026-08-07T11:20:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Blinkit (Food)',
    status: 'completed',
  },
  {
    id: 'tx-aug-25',
    recipient: 'Zepto',
    upiId: 'zepto@axisbank',
    amount: 380,
    date: '2026-08-03T19:15:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Zepto (Food)',
    status: 'completed',
  },

  // Shopping transactions
  {
    id: 'tx-aug-26',
    recipient: 'Amazon',
    upiId: 'amazonpay@apl',
    amount: 1200,
    date: '2026-08-21T15:00:00',
    category: 'Shopping',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Amazon (Shopping)',
    status: 'completed',
  },
  {
    id: 'tx-aug-27',
    recipient: 'Flipkart',
    upiId: 'flipkart@axisbank',
    amount: 800,
    date: '2026-08-14T18:45:00',
    category: 'Shopping',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Flipkart (Shopping)',
    status: 'completed',
  },

  // Transport transactions
  {
    id: 'tx-aug-28',
    recipient: 'Rapido',
    upiId: 'rapido@icici',
    amount: 85,
    date: '2026-08-24T18:00:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Rapido (Transport)',
    status: 'completed',
  },
  {
    id: 'tx-aug-29',
    recipient: 'Rapido',
    upiId: 'rapido@icici',
    amount: 95,
    date: '2026-08-22T09:30:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Rapido (Transport)',
    status: 'completed',
  },
  {
    id: 'tx-aug-30',
    recipient: 'Rapido',
    upiId: 'rapido@icici',
    amount: 110,
    date: '2026-08-20T19:15:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Rapido (Transport)',
    status: 'completed',
  },
  {
    id: 'tx-aug-31',
    recipient: 'Uber',
    upiId: 'uber.india@hdfcbank',
    amount: 280,
    date: '2026-08-18T22:30:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Uber (Transport)',
    status: 'completed',
  },
  {
    id: 'tx-aug-32',
    recipient: 'Indian Oil',
    upiId: 'iocldelhi@sbi',
    amount: 600,
    date: '2026-08-15T12:00:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Indian Oil (Transport)',
    status: 'completed',
  },
  {
    id: 'tx-aug-33',
    recipient: 'Metro Rail',
    upiId: 'dmrc@sbi',
    amount: 150,
    date: '2026-08-09T08:30:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Metro Rail (Transport)',
    status: 'completed',
  },
  {
    id: 'tx-aug-34',
    recipient: 'Metro Rail',
    upiId: 'dmrc@sbi',
    amount: 200,
    date: '2026-08-02T09:00:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Metro Rail (Transport)',
    status: 'completed',
  },
  {
    id: 'tx-aug-35',
    recipient: 'Rapido',
    upiId: 'rapido@icici',
    amount: 90,
    date: '2026-08-01T17:50:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Rapido (Transport)',
    status: 'completed',
  },

  // Entertainment transactions
  {
    id: 'tx-aug-36',
    recipient: 'BookMyShow',
    upiId: 'bookmyshow@icici',
    amount: 680,
    date: '2026-08-21T19:30:00',
    category: 'Entertainment',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: BookMyShow (Entertainment)',
    status: 'completed',
  },
  {
    id: 'tx-aug-37',
    recipient: 'Spotify',
    upiId: 'spotify@hdfcbank',
    amount: 119,
    date: '2026-08-15T00:01:00',
    category: 'Entertainment',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Spotify (Entertainment)',
    status: 'completed',
  },
  {
    id: 'tx-aug-38',
    recipient: 'Prime Video',
    upiId: 'amazonprime@apl',
    amount: 299,
    date: '2026-08-10T14:20:00',
    category: 'Entertainment',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Prime Video (Entertainment)',
    status: 'completed',
  },
  {
    id: 'tx-aug-39',
    recipient: 'Steam Games',
    upiId: 'steam@novaplay',
    amount: 503,
    date: '2026-08-06T23:15:00',
    category: 'Entertainment',
    classificationType: 'user_classified',
    confidence: 0.9,
    classificationReason: 'User classified as Entertainment',
    status: 'completed',
  },

  // Education transactions
  {
    id: 'tx-aug-40',
    recipient: 'Coursera',
    upiId: 'coursera@icici',
    amount: 1000,
    date: '2026-08-16T15:30:00',
    category: 'Education',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Coursera (Education)',
    status: 'completed',
  },

  // Healthcare & Bills & Other
  {
    id: 'tx-aug-41',
    recipient: 'Apollo Pharmacy',
    upiId: 'apollopharmacy@hdfcbank',
    amount: 450,
    date: '2026-08-19T11:30:00',
    category: 'Healthcare',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Apollo Pharmacy (Healthcare)',
    status: 'completed',
  },
  {
    id: 'tx-aug-42',
    recipient: 'Airtel',
    upiId: 'airtelrecharge@airtel',
    amount: 349,
    date: '2026-08-05T10:00:00',
    category: 'Bills',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Airtel (Bills)',
    status: 'completed',
  },
  {
    id: 'tx-aug-43',
    recipient: 'Jio Fiber',
    upiId: 'jiofiber@jio',
    amount: 699,
    date: '2026-08-01T12:00:00',
    category: 'Bills',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Jio Fiber (Bills)',
    status: 'completed',
  },
  {
    id: 'tx-aug-44',
    recipient: 'Suresh Kumar',
    upiId: 'suresh.k@okaxis',
    amount: 322,
    date: '2026-08-14T16:00:00',
    category: 'Other',
    classificationType: 'user_classified',
    confidence: 0.8,
    classificationReason: 'User classified as Other',
    status: 'completed',
  },

  // ==================== JULY 2026 (Previous Month) ====================
  {
    id: 'tx-jul-01',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 20,
    date: '2026-07-30T17:30:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-jul-02',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 30,
    date: '2026-07-28T09:00:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    classificationReason: 'Auto-categorized from previous payments',
    status: 'completed',
  },
  {
    id: 'tx-jul-03',
    recipient: 'Swiggy',
    upiId: 'swiggy@icici',
    amount: 320,
    date: '2026-07-26T13:00:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Swiggy',
    status: 'completed',
  },
  {
    id: 'tx-jul-04',
    recipient: 'Zomato',
    upiId: 'zomato@hdfcbank',
    amount: 450,
    date: '2026-07-22T20:45:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Zomato',
    status: 'completed',
  },
  {
    id: 'tx-jul-05',
    recipient: 'Blinkit',
    upiId: 'blinkit@icici',
    amount: 520,
    date: '2026-07-15T10:30:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Blinkit',
    status: 'completed',
  },
  {
    id: 'tx-jul-06',
    recipient: 'Rohit Kumar',
    upiId: 'rohit.kumar99@paytm',
    amount: 400,
    date: '2026-07-25T18:00:00',
    category: 'Food',
    classificationType: 'multi_purpose_suggested',
    confidence: 0.75,
    classificationReason: 'Suggested Food',
    status: 'completed',
  },
  {
    id: 'tx-jul-07',
    recipient: 'Rohit Kumar',
    upiId: 'rohit.kumar99@paytm',
    amount: 600,
    date: '2026-07-10T15:00:00',
    category: 'Personal',
    classificationType: 'user_classified',
    confidence: 0.85,
    classificationReason: 'User classified as Personal',
    status: 'completed',
  },
  {
    id: 'tx-jul-08',
    recipient: 'Myntra',
    upiId: 'myntrapay@icici',
    amount: 2200,
    date: '2026-07-20T16:00:00',
    category: 'Shopping',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Myntra',
    status: 'completed',
  },
  {
    id: 'tx-jul-09',
    recipient: 'Amazon',
    upiId: 'amazonpay@apl',
    amount: 1100,
    date: '2026-07-12T14:00:00',
    category: 'Shopping',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Amazon',
    status: 'completed',
  },
  {
    id: 'tx-jul-10',
    recipient: 'Uber',
    upiId: 'uber.india@hdfcbank',
    amount: 450,
    date: '2026-07-27T08:30:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Uber',
    status: 'completed',
  },
  {
    id: 'tx-jul-11',
    recipient: 'Rapido',
    upiId: 'rapido@icici',
    amount: 90,
    date: '2026-07-19T18:00:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Rapido',
    status: 'completed',
  },
  {
    id: 'tx-jul-12',
    recipient: 'Indian Oil',
    upiId: 'iocldelhi@sbi',
    amount: 700,
    date: '2026-07-08T11:00:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Indian Oil',
    status: 'completed',
  },
  {
    id: 'tx-jul-13',
    recipient: 'Netflix',
    upiId: 'netflix.india@axisbank',
    amount: 199,
    date: '2026-07-24T10:00:00',
    category: 'Entertainment',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Netflix',
    status: 'completed',
  },
  {
    id: 'tx-jul-14',
    recipient: 'Udemy',
    upiId: 'udemy@icici',
    amount: 1200,
    date: '2026-07-16T17:30:00',
    category: 'Education',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Udemy',
    status: 'completed',
  },
  {
    id: 'tx-jul-15',
    recipient: 'Airtel',
    upiId: 'airtelrecharge@airtel',
    amount: 349,
    date: '2026-07-05T10:00:00',
    category: 'Bills',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Airtel',
    status: 'completed',
  },
  {
    id: 'tx-jul-16',
    recipient: 'Jio Fiber',
    upiId: 'jiofiber@jio',
    amount: 699,
    date: '2026-07-01T12:00:00',
    category: 'Bills',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    classificationReason: 'Recognized merchant: Jio Fiber',
    status: 'completed',
  },

  // ==================== JUNE 2026 ====================
  {
    id: 'tx-jun-01',
    recipient: 'Swiggy',
    upiId: 'swiggy@icici',
    amount: 350,
    date: '2026-06-25T13:00:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    status: 'completed',
  },
  {
    id: 'tx-jun-02',
    recipient: 'Zomato',
    upiId: 'zomato@hdfcbank',
    amount: 490,
    date: '2026-06-20T20:30:00',
    category: 'Food',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    status: 'completed',
  },
  {
    id: 'tx-jun-03',
    recipient: 'Ramesh Kumar',
    upiId: 'ramesh.kumar@okaxis',
    amount: 20,
    date: '2026-06-28T17:00:00',
    category: 'Food',
    classificationType: 'merchant_memory',
    confidence: 0.98,
    status: 'completed',
  },
  {
    id: 'tx-jun-04',
    recipient: 'Amazon',
    upiId: 'amazonpay@apl',
    amount: 2100,
    date: '2026-06-18T16:00:00',
    category: 'Shopping',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    status: 'completed',
  },
  {
    id: 'tx-jun-05',
    recipient: 'Uber',
    upiId: 'uber.india@hdfcbank',
    amount: 380,
    date: '2026-06-15T09:00:00',
    category: 'Transport',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    status: 'completed',
  },
  {
    id: 'tx-jun-06',
    recipient: 'Coursera',
    upiId: 'coursera@icici',
    amount: 1500,
    date: '2026-06-10T14:00:00',
    category: 'Education',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    status: 'completed',
  },
  {
    id: 'tx-jun-07',
    recipient: 'Netflix',
    upiId: 'netflix.india@axisbank',
    amount: 199,
    date: '2026-06-24T10:00:00',
    category: 'Entertainment',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    status: 'completed',
  },
  {
    id: 'tx-jun-08',
    recipient: 'Airtel',
    upiId: 'airtelrecharge@airtel',
    amount: 349,
    date: '2026-06-05T10:00:00',
    category: 'Bills',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    status: 'completed',
  },
  {
    id: 'tx-jun-09',
    recipient: 'Jio Fiber',
    upiId: 'jiofiber@jio',
    amount: 699,
    date: '2026-06-01T12:00:00',
    category: 'Bills',
    classificationType: 'auto_merchant',
    confidence: 0.99,
    status: 'completed',
  },
];
